import Card from "@/components/Card";
import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";

export default function Home() {

  const [categories, setCategories] = useState([]);

  useEffect(() => {
    const categories = async function () {
      const res = await axios.get(
        "http://localhost:1337/api/categories?populate=*"
      );
      // console.log(res.data.data)
      setCategories(res.data.data);
    };
    categories();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* <h1 className='text-3xl font-bold underline'>Hello world!</h1> */}
        <div className="grid grid-cols-1 gap-0 md:grid-cols-2 lg:grid-cols-3">
          {
            categories.length && categories.map((element)=>{
              return (
                <>
                  <div key={element.id}>
                    {/* <h1>{console.log(element.attributes.slug)}</h1> */}
                    <Link href={`/categories/${element.attributes.slug}`}>
                      <Card
                        image={`http://localhost:1337${element.attributes.image.data.attributes.url}`}
                        title={element.attributes.name}
                        description={element.attributes.description}
                      />
                    </Link>
                  </div>
                </>
              );
            })
          }
        </div>
      </main>
    </>
  );
}
